# Consommation des moteurs.

In [1]:
import os
from glob import glob
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import tabata as tbt
from tabata import Opset
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

%reload_ext autoreload
%autoreload 2

In [14]:
datadir = "../data/"
datafiles = glob(os.path.join(datadir,'*.h5'))
sorting = lambda name: int(name[8:])

In [15]:
phaselist = ['climb', 'cruise', 'descend']

In [18]:
from utils import get_consumption

R = []
df = pd.DataFrame()
for acfile in datafiles:
    ac = Opset(acfile, sortkey=sorting)
    for phase in phaselist:
        df = get_consumption(ac, phase=phase)
        df['phase'] = phase
        df['AC'] = 'AC'+ac.storename[-5:-3]
        cols = df.columns
        df = df[['AC','ENG','Flight','phase'] + list(cols[3:-1])]
        R += [df]
        break
    break
df = pd.concat(R)

Record is incomplete
438

,AC,ENG,Flight,Duration,Alt_max,Alt_slope,Avg_egt,TAT_max,TAT_min,T_oil_range,M_max,Volume,Weight,phase
0,AC01,Left,0,0.276389,39439.264501,0.640898,37.642997,1595.692263,40.814093,-22.163944,13.334751,824.614809,1204.548889,climb
1,AC01,Right,0,0.276389,39439.264501,0.640898,37.642997,1595.692263,40.814093,-22.163944,15.468311,825.452162,1204.548889,climb
2,AC01,Left,1,0.287500,39457.811063,0.649114,36.044840,1618.325758,40.543801,-20.271900,15.468311,874.681045,1274.113339,climb
3,AC01,Right,1,0.287500,39457.811063,0.649114,36.044840,1618.325758,40.543801,-20.271900,16.535091,870.679693,1274.113339,climb
4,AC01,Left,2,0.311944,40825.620025,0.624464,34.549785,1576.888217,32.164749,-29.191536,22.935771,896.926225,1304.147323,climb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,AC01,Right,999,0.279722,39545.907234,0.632681,37.309532,1572.905725,31.083580,-32.705333,17.068481,838.173947,1222.435019,climb
1986,AC01,Left,1000,0.236111,35961.784090,0.608031,39.307802,1548.411245,33.786501,-26.218324,19.202041,714.770538,1044.648894,climb
1987,AC01,Right,1000,0.236111,35961.784090,0.608031,39.307802,1548.411245,33.786501,-26.218324,20.802211,716.255344,1044.648894,climb
1988,AC01,Left,1001,0.215000,34876.810202,0.591598,42.838006,1584.599016,29.191536,-24.326280,16.535091,678.317271,991.479518,climb
1989,AC01,Right,1001,0.215000,34876.810202,0.591598,42.838006,1584.599016,29.191536,-24.326280,17.068481,679.873850,991.479518,climb

['AC',
 'ENG',
 'Flight',
 'phase',
 'Duration',
 'Alt_max',
 'Alt_slope',
 'Avg_egt',
 'TAT_max',
 'TAT_min',
 'T_oil_range',
 'M_max',
 'Volume',
 'Weight']